Repository woowa-techcamp-2020/bmart-7, pull requests merged in 2020-08, with the labels that each got.

#11 Feature/#10/back port forwarding setting
  .vscode/settings.json
  server/package-lock.json
  server/package.json
Labels: Backend, env

#12 Feature/#6/back passport GitHub login
  .gitignore
  server/config/github-config.ts
  server/jest.config.js
  server/package-lock.json
  server/package.json
  server/router.ts
  server/server.ts
  server/utils/jwt.ts
Labels: Backend, feature

#13 Feature/#9/front login component
  client/package-lock.json
  client/package.json
  client/public/images/bmartlogo.jpeg
  client/src/App.tsx
  client/src/app.scss
  client/src/components/Login/index.tsx
  client/src/components/Login/login.scss
Labels: feature, frontend

#20 Feature/#16/backend user api
  server/graphql/user/user-resolver.ts
  server/graphql/user/user.graphql
  server/prisma/schema.prisma
Labels: Backend, feature

#27 Feature/#24/back GitHub login
  client/package-lock.json
  client/package.json
  client/src/components/Login/index.tsx
  server/package-lock.json
  server/package.json
  server/router.ts
  server/server.ts
  server/utils/jwt.ts
Labels: Backend, feature

#29 Feature/#16/Backend User Api
  server/graphql/user/user-resolver.ts
  server/graphql/user/user.graphql
Labels: Backend, update

#28 Feature/#22/front login btn component
  README.md
  client/src/App.tsx
  client/src/components/Login/index.tsx
  client/src/components/Login/login.scss
  client/src/components/SocialLoginBtn/index.tsx
  client/src/components/SocialLoginBtn/socialLoginBtn.scss
  client/src/reset.scss
Labels: feature, frontend

#37 Feature/#26 front style setting
  client/src/App.tsx
  client/src/app.scss
  client/src/components/Login/login.scss
  client/src/components/SocialLoginBtn/socialLoginBtn.scss
  client/src/styles/_definitions.scss
  client/src/styles/_mixins.scss
  client/src/styles/_package.scss
  client/src/styles/base.scss
  client/src/styles/fonts.scss
  client/src/styles/reset.scss
Labels: feature, frontend

#39 Feature/#36/back prisma improvement
  server/graphql/context.ts
  server/package.json
  server/prisma/index.ts
  server/router.ts
Labels: Backend, feature, update

#41 Env/#19/front eslint prettier
  .eslintrc.js
  .prettierrc
  client/.eslintrc.js
  client/.prettierrc
  client/package-lock.json
  client/package.json
  client/src/ApolloClient.ts
  client/src/components/Login/index.tsx
  client/src/components/SocialLoginBtn/index.tsx
Labels: env, frontend

#43 Env/#42/back eslint prettier
  .vscode/settings.json
  server/.eslintrc.js
  server/.prettierrc
  server/graphql/index.ts
  server/package-lock.json
  server/package.json
  server/server.ts
Labels: Backend, env

#44 Feature/#40 front custom snippet
  .vscode/bamrt7.code-snippets
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/app.scss
  client/src/components/Login/config.ts
  client/src/components/Login/index.tsx
  client/src/components/Login/style.scss
  client/src/components/SocialLoginBtn/index.tsx
  client/src/components/SocialLoginBtn/style.scss
  client/src/pages/LoginPage.tsx
  client/tsconfig.json
  client/tsconfig.paths.json
Labels: env, frontend

#45 Feature/#38/front react router
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Login/config.ts
Labels: feature, frontend

#49 Feature/#47/back favorite api
  client/package-lock.json
  client/package.json
  server/graphql/category/category.graphql
  server/graphql/product/product.graphql
  server/graphql/user/user-resolver.ts
  server/graphql/user/user.graphql
  server/prisma/schema.prisma
  server/server.ts
Labels: Backend, feature, update

#50 Feature/#48/front favorite
  .vscode/bamrt7.code-snippets
  .vscode/settings.json
  client/.prettierrc
  client/craco.config.js
  client/src/App.tsx
  client/src/app.scss
  client/src/components/Product/index.tsx
  client/src/components/Product/style.scss
  client/src/components/ProductList/index.tsx
  client/src/components/ProductList/style.scss
  client/src/pages/FavoritePage/gql.ts
  client/src/pages/FavoritePage/index.tsx
  client/src/pages/FavoritePage/style.scss
  client/src/store.ts
  client/src/styles/_definitions.scss
  client/src/styles/_mixins.scss
  client/src/styles/base.scss
  client/src/types.ts
  client/src/utils/index.ts
  server/.prettierrc
  server/graphql/category/category-resolver.ts
  server/graphql/index.ts
  server/graphql/product/product-resolver.ts
  server/graphql/product/product.graphql
  server/package.json
Labels: Backend, feature, frontend, update

#56 Feature/#52/front product update
  client/src/components/Product/index.tsx
  client/src/components/Product/style.scss
  client/src/components/common/Product/gql.ts
  client/src/components/common/Product/index.tsx
  client/src/components/common/Product/style.scss
  client/src/components/common/ProductList/index.tsx
  client/src/components/common/ProductList/style.scss
  client/src/pages/FavoritePage/index.tsx
  client/src/styles/base.scss
  server/graphql/user/user-resolver.ts
Labels: Backend, feature, frontend, update

#54 Feature/#33/front carousel component
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/components/Carousel/index.tsx
  client/src/components/Carousel/practice.scss
  client/src/components/Carousel/practice.tsx
  client/src/components/Carousel/style.scss
  client/src/components/Login/index.tsx
  client/src/pages/MainPage/gql.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/style.scss
  package-lock.json
Labels: feature, frontend

#59 Feature/#58 back use s3
  server/graphql/category/category.graphql
  server/graphql/index.ts
  server/graphql/product/product-resolver.ts
  server/graphql/product/product.graphql
  server/prisma/schema.prisma
  server/router.ts
  server/utils/crwaling.ts
  server/utils/data.json
  server/utils/data.ts
Labels: Backend, feature, update

#67 Feature/#53/main category
  client/public/mainIcons/1.jpeg
  client/public/mainIcons/10.jpeg
  client/public/mainIcons/2.jpeg
  client/public/mainIcons/3.jpeg
  client/public/mainIcons/4.jpeg
  client/public/mainIcons/5.jpeg
  client/public/mainIcons/6.jpeg
  client/public/mainIcons/7.jpeg
  client/public/mainIcons/8.jpeg
  client/public/mainIcons/9.jpeg
  client/src/App.tsx
  client/src/components/Login/style.scss
  client/src/components/MainPage/MainCategoryList/MainCategoryItem/index.tsx
  client/src/components/MainPage/MainCategoryList/MainCategoryItem/style.scss
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/MainPage/MainCategoryList/style.scss
  client/src/components/SocialLoginBtn/index.tsx
  client/src/components/SocialLoginBtn/style.scss
  client/src/components/common/Carousel/index.tsx
  client/src/components/common/Carousel/style.scss
  client/src/components/common/Carousel/temporary/practice.scss
  client/src/components/common/Carousel/temporary/practice.tsx
  client/src/pages/LoginPage/LoginPage.tsx
  client/src/pages/MainPage/index.tsx
  client/src/styles/base.scss
Labels: feature, frontend

#65 Feature/#60 product api test page
  client/src/App.tsx
  client/src/components/common/Product/gql.ts
  client/src/components/common/Product/index.tsx
  client/src/components/common/Product/style.scss
  client/src/components/common/ProductList/index.tsx
  client/src/components/common/ProductList/style.scss
  client/src/pages/FavoritePage/gql.ts
  client/src/pages/TestPage/gql.ts
  client/src/pages/TestPage/index.tsx
  client/src/types.ts
  server/graphql/product/product-resolver.ts
  server/graphql/product/product.graphql
  server/utils/crwaling.ts
  server/utils/data.ts
Labels: Backend, feature, frontend, update

#69 Feature/#64/front category preview component
  client/src/components/CategoryPreview/gql.ts
  client/src/components/CategoryPreview/index.tsx
  client/src/components/CategoryPreview/style.scss
  client/src/components/RecommendedContainer/index.tsx
  client/src/components/RecommendedContainer/style.scss
  client/src/pages/MainPage/index.tsx
  server/graphql/product/product-resolver.ts
  server/graphql/product/product.graphql
Labels: Backend, feature, frontend

#72 Feature/#61 front product slide
  client/src/components/CategoryPreview/gql.ts
  client/src/components/CategoryPreview/index.tsx
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/RecommendedContainer/gql.ts
  client/src/components/RecommendedContainer/index.tsx
  client/src/components/common/Carousel/style.scss
  client/src/components/common/Divider/index.tsx
  client/src/components/common/Divider/style.scss
  client/src/components/common/Product/index.tsx
  client/src/components/common/Product/style.scss
  client/src/components/common/ProductList/index.tsx
  client/src/components/common/ProductSlide/index.tsx
  client/src/components/common/ProductSlide/style.scss
  client/src/pages/MainPage/gql.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/TestPage/gql.ts
  client/src/pages/TestPage/index.tsx
  client/src/styles/_definitions.scss
  client/src/styles/base.scss
  client/src/styles/reset.scss
  server/graphql/product/product-resolver.ts
  server/graphql/product/product.graphql
Labels: Backend, feature, frontend, update

#74 Feature/#73 Front Divider
  client/src/components/common/Divider/index.tsx
  client/src/components/common/Divider/style.scss
  client/src/pages/MainPage/index.tsx
Labels: feature, frontend

#101 Feature/#95/front header
  client/public/images/bmart-logo.png
  client/src/components/MainPage/CategoryPreviewHeader/style.scss
  client/src/components/common/Filter/index.tsx
  client/src/components/common/Header/index.tsx
  client/src/components/common/Header/style.scss
  client/src/components/common/SubHeader/style.scss
  client/src/pages/CategoryPage/gql.ts
  client/src/pages/CategoryPage/index.tsx
  client/src/pages/FavoritePage/index.tsx
  client/src/pages/MainCategoryPage/index.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/style.scss
  client/src/store/index.tsx
  client/src/styles/_definitions.scss
  server/graphql/category/category-resolver.ts
  server/graphql/category/category.graphql
Labels: Backend, feature, frontend, update

#114 Feature/#104/front main page style
  client/src/components/Login/index.tsx
  client/src/components/MainPage/CategoryPreview/index.tsx
  client/src/components/MainPage/CategoryPreview/style.scss
  client/src/components/MainPage/CategoryPreviewHeader/style.scss
  client/src/components/MainPage/CategoryPreviewSection/index.tsx
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/MainPage/PreviewContainer/index.tsx
  client/src/components/MainPage/PreviewContainer/style.scss
  client/src/components/MainPage/RecommendedContainer/index.tsx
  client/src/components/MainPage/RecommendedContainer/style.scss
  client/src/components/common/Product/CartIcon.tsx
  client/src/components/common/Product/HeartIcon.tsx
  client/src/components/common/Product/gql.ts
  client/src/components/common/Product/index.tsx
  client/src/components/common/ProductList/index.tsx
  client/src/components/common/ProductSlide/style.scss
  client/src/pages/MainPage/index.tsx
  client/src/styles/_mixins.scss
Labels: feature, frontend, update

#120 Feature/#71/preview container 2
  client/src/components/MainPage/PreviewContainer/index.tsx
  server/graphql/product/product.graphql
Labels: frontend, update

#121 Feature/#115/back cart item
  server/graphql/cart/cart-resolver.ts
  server/graphql/cart/cart.graphql
  server/graphql/index.ts
  server/package-lock.json
  server/package.json
  server/prisma/schema.prisma
Labels: Backend, feature

#129 Feature/#99/side page
  client/src/App.tsx
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/MainPage/MainCategoryList/style.scss
  client/src/components/SidePage/CategoryContainer/SubCategoryContainer/index.tsx
  client/src/components/SidePage/CategoryContainer/SubCategoryContainer/style.scss
  client/src/components/SidePage/CategoryContainer/index.tsx
  client/src/components/SidePage/CategoryContainer/mock.json
  client/src/components/SidePage/CategoryContainer/style.scss
  client/src/components/SidePage/SideMenuHeader/index.tsx
  client/src/components/SidePage/SideMenuHeader/style.scss
  client/src/components/common/Carousel/index.tsx
  client/src/pages/SidePage/index.tsx
  client/src/pages/SidePage/style.scss
  client/src/styles/_definitions.scss
  server/graphql/product/product-resolver.ts
Labels: feature, frontend, update

#131 Feature/#123/front cart page
  client/public/images/empty-cart.jpeg
  client/src/App.tsx
  client/src/components/CartPage/CartItem/Count.tsx
  client/src/components/CartPage/CartItem/Price.tsx
  client/src/components/CartPage/CartItem/RemoveButton.tsx
  client/src/components/CartPage/CartItem/gql.ts
  client/src/components/CartPage/CartItem/index.tsx
  client/src/components/CartPage/CartItem/style.scss
  client/src/components/CartPage/CartList/index.tsx
  client/src/components/CartPage/CartList/style.scss
  client/src/components/CartPage/CartSummary/index.tsx
  client/src/components/CartPage/CartSummary/style.scss
  client/src/components/CartPage/EmptyCart/index.tsx
  client/src/components/CartPage/EmptyCart/style.scss
  client/src/components/common/CartFloatButton/index.tsx
  client/src/components/common/CartFloatButton/style.scss
  client/src/pages/CartPage/index.tsx
  client/src/pages/FavoritePage/index.tsx
  client/src/pages/MainPage/style.scss
  client/src/styles/_mixins.scss
  server/graphql/product/product-resolver.ts
Labels: feature, frontend

#138 Feature/#123/front cart page
  client/src/components/common/Product/CartIcon.tsx
  client/src/components/common/Product/gql.ts
  client/src/components/common/Product/style.scss
  client/src/store/gql.ts
  client/src/store/index.tsx
Labels: feature, frontend, update

#136 Feature/#127/detail page
  client/public/mainIcons/1.jpeg
  client/public/mainIcons/1.png
  client/public/mainIcons/10.jpeg
  client/public/mainIcons/10.png
  client/public/mainIcons/2.jpeg
  client/public/mainIcons/2.png
  client/public/mainIcons/3.jpeg
  client/public/mainIcons/3.png
  client/public/mainIcons/4.jpeg
  client/public/mainIcons/4.png
  client/public/mainIcons/5.jpeg
  client/public/mainIcons/5.png
  client/public/mainIcons/6.jpeg
  client/public/mainIcons/6.png
  client/public/mainIcons/7.jpeg
  client/public/mainIcons/7.png
  client/public/mainIcons/8.jpeg
  client/public/mainIcons/8.png
  client/public/mainIcons/9.jpeg
  client/public/mainIcons/9.png
  client/public/productImg/food1.jpeg
  client/public/productImg/food2.jpeg
  client/public/productImg/food3.jpeg
  client/public/productImg/food4.jpeg
  client/src/App.tsx
  client/src/components/DetailPage/DetailMainContainer/ProductCommon/index.tsx
  client/src/components/DetailPage/DetailMainContainer/ProductCommon/style.scss
  client/src/components/DetailPage/DetailMainContainer/gql.ts
  client/src/components/DetailPage/DetailMainContainer/index.tsx
  client/src/components/DetailPage/DetailMainContainer/style.scss
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/MainPage/MainCategoryList/style.scss
  client/src/components/MainPage/PreviewContainer/index.tsx
  client/src/components/common/Carousel/index.tsx
  client/src/components/common/Product/index.tsx
  client/src/pages/DetailPage/index.tsx
  client/src/pages/DetailPage/style.scss
  client/src/styles/_definitions.scss
Labels: feature, frontend, update

#142 Feature/#137/main category container
  client/src/components/CartPage/CartItem/index.tsx
  client/src/components/MainPage/MainCategoryList/MainCategoryItem/index.tsx
  client/src/components/MainPage/MainCategoryList/MainCategoryItem/style.scss
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/MainPage/MainCategoryList/style.scss
  client/src/components/MainPage/PreviewContainer/index.tsx
  client/src/components/common/Product/index.tsx
  client/src/components/common/Product/style.scss
  client/src/pages/MainPage/gql.ts
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/style.scss
  client/src/types.ts
  server/graphql/category/category-resolver.ts
  server/graphql/category/category.graphql
Labels: Backend, feature, frontend, update

#146 Feature/#147/front cart end
  client/public/mainIcons/1.png
  client/public/mainIcons/10.png
  client/public/mainIcons/2.png
  client/public/mainIcons/3.png
  client/public/mainIcons/4.png
  client/public/mainIcons/5.png
  client/public/mainIcons/6.png
  client/public/mainIcons/7.png
  client/public/mainIcons/8.png
  client/public/mainIcons/9.png
  client/src/components/CartPage/CartItem/RemoveButton.tsx
  client/src/components/CartPage/CartItem/index.tsx
  client/src/components/CartPage/CartItem/style.scss
  client/src/components/CartPage/CartList/index.tsx
  client/src/components/CartPage/CartSelectBar/index.tsx
  client/src/components/CartPage/CartSelectBar/style.scss
  client/src/components/CartPage/OrderButton/index.tsx
  client/src/components/CartPage/OrderButton/style.scss
  client/src/components/MainCategoryPage/CategoryList/style.scss
  client/src/components/MainPage/MainCategoryList/MainCategoryItem/style.scss
  client/src/components/MainPage/MainCategoryList/index.tsx
  client/src/components/SidePage/CategoryContainer/SubCategoryContainer/index.tsx
  client/src/components/common/Filter/index.tsx
  client/src/pages/CartPage/index.tsx
  client/src/types.ts
Labels: feature, frontend, update

#148 Feature/#135/update side page
  client/src/components/DetailPage/DetailMainContainer/index.tsx
  client/src/components/SidePage/CategoryContainer/SubCategoryContainer/index.tsx
  client/src/components/SidePage/CategoryContainer/gql.ts
  client/src/components/SidePage/CategoryContainer/index.tsx
  client/src/components/SidePage/CategoryContainer/mock.json
  client/src/components/SidePage/CategoryContainer/style.scss
  client/src/components/SidePage/SideMenuHeader/style.scss
  client/src/components/common/Header/style.scss
  client/src/pages/SidePage/index.tsx
  client/src/pages/SidePage/style.scss
Labels: feature, frontend, update

#152 Feature/#150/order page
  client/public/images/orderIcon.png
  client/src/App.tsx
  client/src/components/OrderPage/OrderRecordContainer/index.tsx
  client/src/components/OrderPage/OrderRecordContainer/style.scss
  client/src/components/SidePage/SideMenuHeader/index.tsx
  client/src/pages/OrderPage/index.tsx
  client/src/pages/OrderPage/style.scss
Labels: feature, frontend
